name = "prisma-clerk-test"
main = "src/index.ts"
compatibility_date = "2024-01-09"

# Add this section for better compatibility
compatibility_flags = [
  "nodejs_compat"
]

# Your environment variables
[vars]
DATABASE_URL=""
DIRECT_URL = ""
CLERK_SECRET_KEY=""

# Add this to allow Prisma to work in the Worker environment
[build]
command = "npm run build"
watch_dir = "src"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]